[project]
name = "async-e-isso"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pablo Aguilar" }
]
requires-python = ">=3.14"
dependencies = []

[tool.pytest]
minversion = "9.1"
norecursedirs = [
    "*.egg",
    ".eggs",
    "dist",
    "build",
    ".git",
    "__pycache__",
]
addopts = [
    "--strict-markers",
    "--strict-config",
]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "pytest>=9.1",
    "pytest-codspeed>=5.0.3",
]
