name: CodSpeed

on:
  push:
    branches: [ main, with-gil, without-gil ]
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          run: uv run pytest tests/ --codspeed
